
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class frame extends javax.swing.JFrame {
    
  
   
    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        encrypt = new javax.swing.JButton();
        decrypt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        fsave = new javax.swing.JButton();
        keyC = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" ABABIYA TUJUMA  0297/12  (ENCRYPTION /DECRYPTION)");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        encrypt.setText("Encrypt");
        encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptActionPerformed(evt);
            }
        });

        decrypt.setText("Decrypt");
        decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Display");

        pathField.setText(" ");

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        fsave.setText("Save All");
        fsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsaveActionPerformed(evt);
            }
        });

        keyC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        keyC.setSelectedIndex(3);
        keyC.setToolTipText("choose shift key");
        keyC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyCActionPerformed(evt);
            }
        });

        jLabel2.setText("Key");

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caeser cipher", "vernam's" }));

        jLabel3.setText("Choose Encryption/Decryption Method");

        jLabel4.setBackground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Path");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(fsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(keyC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(browse))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(decrypt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(encrypt, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(encrypt)
                        .addGap(18, 18, 18)
                        .addComponent(decrypt)
                        .addGap(18, 18, 18)
                        .addComponent(clear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browse)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fsave)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("  Caesar cipher :\nIs a simple method of encoding messages. Caesar ciphers use a substitution\nmethod where letters in the alphabet are shifted by some fixed number of\nspaces to yield an encoding alphabet. \nA Caesar cipher with a shift of 1 would encode an A as a B, an M as an N,\nand a Z as an A, and so on.\n\nEncrypt : helps you to encode a plain text on the text area.\nDecrypt : helps you to Decode the cipher text you already encoded.\n\nSave All : helps you to save any encoded or plain text written on the text \n            area.\nBrowse:  helps you to browse any text file from any directory.\n\nClear : helps you to clear the path field and text area for fresh start\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Help", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsaveActionPerformed
        try{
            JFileChooser fileSaver= new JFileChooser();
            fileSaver.showSaveDialog(null);
            File file=fileSaver.getSelectedFile();
            if(!Files.exists(file.toPath())){
                pathField.setText(file.toPath().toString());
                FileWriter write=new FileWriter(file.toPath().toString());
                textArea.write(write);
                textArea.requestFocus();
                
            
            }
            else{
                JOptionPane.showMessageDialog(this,"File name alredy existed \n Change File Name ");
            }
            
        }catch(Exception e){JOptionPane.showMessageDialog(this,"Save Discarded");}
    }//GEN-LAST:event_fsaveActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser chooser = new JFileChooser();                     
       String path;
         int result = chooser.showSaveDialog(null);               // display  save dialog
         
  if(result==JFileChooser.APPROVE_OPTION){                       // if save button is clicked
            File selectedFile=chooser.getSelectedFile();         // get selected file
   path = selectedFile.getAbsolutePath();                         // gets its path
             
            try {
                FileReader reade = new FileReader(path);              //  "FileReader" is a class ,reades the path and get the file ,it also reads the file
                //BufferedReader br = new BufferedReader(reade);        // reads the file line by line
                //br.close();
                textArea.read(reade,null);                    // reads from text area
                textArea.requestFocus();                 // to make the focus on the text area
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "file not found");    //Exception if file not found
            } catch (IOException ex) {
                Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
            }catch(Exception e){
                
            }
            pathField.setText(path);                // displaying the path on the text field
  }
          
       
             
         
        
        
    }//GEN-LAST:event_browseActionPerformed

    private void encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptActionPerformed
int key = Integer.parseInt(keyC.getSelectedItem().toString()); //get selected item from combo box-convert to string-store it as an integer since key is int type
String message = textArea.getText();
textArea.setText(encrypt(message,key)); // display encrypted message on the text area
        
    }//GEN-LAST:event_encryptActionPerformed

    private void keyCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyCActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       System.exit(0);   //exit out of the program
    }//GEN-LAST:event_jButton6ActionPerformed

    private void decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptActionPerformed
    int key = Integer.parseInt(keyC.getSelectedItem().toString());
String message = textArea.getText();
textArea.setText(decrypt(message,key));
    }//GEN-LAST:event_decryptActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        textArea.setText("");         //clear 
        pathField.setText("");         //clear
        
    }//GEN-LAST:event_clearActionPerformed

 
    
    
 public static int asciiToCustom(char ascii)     // a mhetod which converts  an array of characters to custom code.( i generated my own custom code 0-94)
{
    int asci=ascii;                            // convert aschii char to its equvalent integer value
  int customCode;
  if(asci >=32 && asci <=126)                 //printable ascii characters which are b/n 32 && 126 (i am gust trying to map (32-126) to (1-94) )
  {
      customCode=asci - 31;          // coverting to custom code ,let 32=1  or 32-x=31 solving for x , x=1
  }
 else if (asci==10)                  // ascii 10 is new line "\n" which is difficult to print ,so i used another else if statement
{
     customCode=asci-10;             // here mapping 10 to 0 , or let 10=0   
 }
  else
  {
       throw new RuntimeException("Insert a valid letter");   // if it is out of bound (0-94) it will be run time Exeption 
  }
    return customCode;
    
}
    public static char customToAscii(int custom){          // method which converts my custom code to ascii code
    int ascii;
        if(custom >=1 && custom <=94){                    // if it is b/n 1 & 94 it just add 31 to reconvert it to its previous place : since 32=1
        ascii= custom +  31;
        }
        else if(custom==0){
        ascii= custom + 10;                             // 0=10
        }
        else{ throw new RuntimeException("not a valid custom code");}
        
      return (char) ascii;      
    }
    public static String encrypt(String plainText, int k){       //  this method takes plaintext and key then perform encryption
    char[] arr=plainText.toCharArray();
    for(int i = 0; i<arr.length;i++){
       
        arr[i]=customToAscii((asciiToCustom(arr[i]) + k ) % 95); //convert char to customCode then add key then perform module then again convert back to ascii code
       
     }
    return String.valueOf(arr);                              //  ascii value(int type) to string 
    }
    public static String decrypt(String cText, int k){    // it is decription method ,takes key an cipher text
         char[] arr=cText.toCharArray();
    for(int i = 0; i<arr.length;i++){
       
        arr[i]=customToAscii((asciiToCustom(arr[i]) + 95 - k % 95) %95);  // i add 95 for the case (ci-key) is negative and i have to module it two times for posetive value since i added 95 
      
   
    }
     return String.valueOf(arr);
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton clear;
    private javax.swing.JButton decrypt;
    private javax.swing.JButton encrypt;
    private javax.swing.JButton fsave;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox keyC;
    private javax.swing.JTextField pathField;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
